apiVersion: v1
kind: Service
metadata:
  name: manager-service-svc
  namespace: dev
spec:
  selector:
    app: manager-service-grpc
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  - name: grpc
    protocol: TCP
    port: 50000
    targetPort: 50000
    nodePort: 30500