apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    name: "{{ .Values.name }}-pod"
    namespace: {{ .Values.namespace }}
  type: ClusterIP
  ports:
    - name: "{{ .Values.service.name }}-port"
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}