apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
  namespace: {{ .Values.namespace }}

spec:
  stripPrefix:
    prefixes:
      - {{ .Values.middleware.prefix_01 }}